### PR TITLE
Animated GIF support.

### PR DESCRIPTION
**Pull request by timonus**
Untested at the moment, but I believe this brings animated GIF support to the PDK.

### CODE REVIEW

**Comment by timonus** [comment]
Alright, verified that this works. I made [this pin](https://www.pinterest.com/pin/128282289366257653/) using this branch of the PDK. Sadly, looks like our service isn't recognizing it as a GIF at the moment (I've fixed that before and will again), but if you click through to the [underlying image](https://s-media-cache-ak0.pinimg.com/originals/c2/30/5c/c2305cc89561a90b61ecbe1a487a2cd0.gif) you'll see it's a GIF.

**Comment by timonus** [comment]
cc @rahul-malik, who pinged me to update this today :) @levi any chance I could land this?

**Comment by rahul-malik** [comment]
Discussed with @timonus in person but leaving feedback here to associate with the thread.
> I can merge this PR when we successfully have a GIF pin created. Although we are uploading a GIF the API is not creating the correct pin type and the GIF does not actually play. When this is resolved I'll help merge this PR.

**Comment by timonus** [comment]
Alright, the [pin I attached](https://www.pinterest.com/pin/128282289366257653/) in the former comment is now being properly recognized as a GIF, and new pins I create are also working (example [here](https://www.pinterest.com/pin/128282289366281822/)). I think this is ready to land @rahul-malik.

**Pull request merged**
